### ISSUE TITLE
Problema al cargar las imagenes en el Github

### ISSUE THREAD

**Issue by lodurr** [maestria-geotel-201902/unidad-1-asignacion-1-datos-espaciales-en-r-lodurr#1]
El problema  es que al ver el documento .md en el Github no se ven las imagenes, sin embargo al realizar el Knit en el RStudio las presenta correctamente. Pense que era por el parametro eval = T y lo cambie a F lo cual no funcionó. Lo mire en otro explorador pero tampoco (Firefox Dev & Chrome) pero en ninguno se ve correctamente.

**Comment by hoyodepelempito** [comment]
Marca el aspa de todo lo que aparece en la pestaña `Git`. Cuando marques el aspa de `img/` verás que se expandirá a todos los archivos de imágenes que se crearon al tejer. A partir de ese punto, puedes hacer *commit>push* y listo.

![image](https://user-images.githubusercontent.com/53181265/67441793-4027e280-f5cc-11e9-8d4d-c1f7f9ba8d6e.png)

**Comment by hoyodepelempito** [comment]
Bueno, te ayudó el estudiante ficticio, no el tali.

**Comment by lodurr** [comment]
Gracias compañero ficticio
